global using Yarp.ReverseProxy.Store;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using ReverseProxy.Store.Entities;
global using Microsoft.Extensions.Primitives;
global using System;
global using System.Threading;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Logging;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net.Http;
global using System.Security.Authentication;
global using System.Security.Cryptography.X509Certificates;
global using Yarp.ReverseProxy.Configuration;
global using HttpClientConfig = ReverseProxy.Store.Entities.HttpClientConfig;
global using RouteHeader = ReverseProxy.Store.Entities.RouteHeader;
global using SessionAffinityConfig = ReverseProxy.Store.Entities.SessionAffinityConfig;
global using RouteQueryParameter = Yarp.ReverseProxy.Configuration.RouteQueryParameter;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.Threading.Tasks;
